main: "de.bypixeltv.skcloudnet.Main"
name: "SkCloudnet"
version: "v1.2"
api-version: "1.20"

author: "byPixelTV"
description: "A Skript-Addon to interact with your CloudNet v4 instance."
website: "https://bypixeltv.me"

libraries:
  - "dev.jorel:commandapi-bukkit-shade:9.3.0"
  - "dev.jorel:commandapi-bukkit-kotlin:9.3.0"
  - "net.axay:kspigot:1.20.3"
  - "org.json:json:20231013"

depend: [Skript]