blank_issues_enabled: false
contact_links:
  - name: 🦆 byPixelTV's Discord
    url: https://dsc.gg/byPixelTV
    about: For general help with SkCloudnet join byPixelTV's Discord
  - name: 🚰 SpigotMC Resource
    url: https://www.spigotmc.org/resources/skcloudnet.116030/
    about: Read about SkCloudnet!