name: Java CI with Gradle

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Extract version
        id: extract_version
        run: echo "VERSION=$(./gradlew properties -q | grep '^version:' | awk '{print $2}')" >> $GITHUB_ENV

      - name: List build/libs directory for debug
        run: ls -al build/libs

      - name: Rename artifact with version and -dev
        run: |
          VERSION=$(echo $VERSION | tr -d '\r')
          echo "Renaming SkCloudnet*.jar to SkCloudnet-$VERSION-dev.jar"
          mv build/libs/SkCloudnet*.jar build/libs/SkCloudnet-$VERSION-dev.jar
        shell: /usr/bin/bash -e {0}
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.3-9/x64
          JAVA_HOME_21_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.3-9/x64
          VERSION: ${{ env.VERSION }}

      - name: List build/libs directory for debug after rename
        run: ls -al build/libs

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SkCloudnet-Artifact
          path: build/libs/SkCloudnet-$VERSION-dev.jar
