name: Java CI with Gradle

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Extract version
        id: extract_version
        run: echo "VERSION=$(./gradlew properties -q | grep '^version:' | awk '{print $2}')" >> $GITHUB_ENV

      - name: Rename artifact with version and -dev
        run: |
          VERSION=$(echo $VERSION | tr -d '\r')
          mv build/libs/SkCloudnet*.jar build/libs/SkCloudnet-$VERSION-dev.jar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SkCloudnet-Artifact
          path: build/libs/SkCloudnet-$VERSION-dev.jar
